# -*- coding: utf-8 -*-
"""ejercicio_matriz.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KWh0gQf3fNOe_PjyP-X_GdEZ8i5Dkk_1
"""

import numpy as np
import random

m1 = [
    [0,0,0],
    [0,0,0],
    [0,0,0]
]

matriz = np.array(m1)

for i in range(3):
  for j in range(3):
    matriz[i][j] = random.randint(0,100)

print(matriz)


print("El promedio de los elementos de la matriz es:", round(matriz.sum()/matriz.size,2))

print("La sumatoria de los elementos de la matriz es:", matriz.sum())

print("El elemento mayor es:", matriz.max())

print("El elemento menor es:", matriz.min())

matriz = np.diag(matriz)
print(matriz)