# -*- coding: utf-8 -*-
"""formativa_sem_7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10nKqxIjVrrVzxjAw-ryfP0rdFuhqMTRY
"""

import numpy as np
import random

m1 = [
    [0,0,0],
    [0,0,0],
    [0,0,0]
]
suma_total = 21

suma_actual = 0

matriz = np.array(m1)

while suma_actual < suma_total:
  for i in range(3):
    for j in range(3):
      if suma_actual < suma_total:
        matriz[i][j] = random.randint(0, suma_total - suma_actual)
        suma_actual += matriz[i][j]

print(matriz)

print("La suma de los elementos es: ", matriz.sum())